{% set minions =  salt['roles.list_minions']('redis-server') -%}
{% set user    = 'git' -%}
# GitLab user. git by default
user:             {{ user }}

# Url to gitlab instance. Used for api calls. Should end with a slash.
gitlab_url:         "http://localhost/"

http_settings:
# user:              someone
# password:          somepass
# ca_file:          /etc/ssl/cert.pem
# ca_path:          /etc/pki/tls/certs
  self_signed_cert:  false

# Repositories path
# Give the canonicalized absolute pathname,
# REPOS_PATH MUST NOT CONTAIN ANY SYMLINK!!!
# Check twice that none of the components is a symlink, including "/home".
repos_path:        "/home/{{ user }}/repositories"

# File used as authorized_keys for gitlab user
auth_file:         "/home/{{ user }}/.ssh/authorized_keys"

{% if minions['redis-server'] %}
# Redis settings used for pushing commit notices to gitlab
redis:
  bin:              /usr/bin/redis-cli
  host:           {{ minions['redis-server'][0] }}
  port:              6379
# socket:           /tmp/redis.socket # Only define this if you want to use sockets
  namespace:         resque:gitlab
{% endif %}

# Log file.
# Default is gitlab-shell.log in the root directory.
# log_file:        "/home/{{ user }}/gitlab-shell/gitlab-shell.log"

# Log level. INFO by default
log_level:           INFO

# Audit usernames.
# Set to true to see real usernames in the logs instead of key ids, which is easier to follow, but
# incurs an extra API call on every gitlab-shell command.
audit_usernames:     false
